from typing import List

from pydantic import BaseModel, Field


class Source(BaseModel):
    """Schema for a source used by the agent."""

    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    """Schema with agent response, with source and answers."""

    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(
        default_factory=list,
        description="List of sources used by the agent to generate the answer",
    )
